# Generated by Django 6.0.4 on 2026-06-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default='Sin comuna', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Pagado', 'Pago Recibido'), ('Preparacion', 'En Preparación'), ('Despacho', 'En Despacho'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='Transferencia Bancaria', max_length=30),
        ),
    ]
