# Generated by Django 6.0.4 on 2026-06-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_pedido_options_pedido_comuna_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Revisando', 'Pago en Revisión'), ('Pagado', 'Pago Aprobado'), ('Preparacion', 'En Preparación'), ('Despacho', 'En Despacho'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
